### Fruit Quality Inspection Analysis â€“ Chile to Netherlands

This project analyzes the quality and condition of fruits arriving at a fruit importer in the Netherlands. The fruits are shipped via refrigerated containers from Chile by sea and inspected upon arrival. 

The dataset contains detailed information about the inspections, including technical variables such as temperature, gas composition, and multiple quality/condition indicators. 

The objective of this analysis is to extract, clean, and explore this data to generate actionable insights regarding fruit losses and other technical or commercial aspects of the season's performance.

The workflow of this notebook includes:

1. Data import and exploration
2. Data cleaning and preparation
3. Exploratory Data Analysis (EDA)
4. Preparation for visualization and reporting (e.g., Tableau)

> Tools used: Python (Pandas, NumPy, Matplotlib/Seaborn), Tableau

In [183]:
# STEP 1: Data Import and Initial Exploration
# -------------------------------------------
# This script imports inspection data from a CSV file and performs basic
# exploration to understand the structure and quality of the dataset.

import pandas as pd

# Load the dataset
file_path = "db.csv"  # adjust path if needed
df = pd.read_csv(file_path)

# Display basic info
print("Shape of the dataset:", df.shape)
print("\nColumn names:\n", df.columns.tolist())
print("\nData types and non-null values:\n")
print(df.info())

# Display column names in a vertical list
print("Column names:\n")
print(pd.Series(df.columns))

# Show sample rows
print("\nSample rows:\n")
print(df.head())

# Describe numerical and categorical data
print("\nStatistical summary:\n")
print(df.describe(include='all'))

Shape of the dataset: (5000, 35)

Column names:
 ['idinspection', 'inspector_name', 'fruit', 'inspection_date', 'container', 'exporter', 'importer', 'vessel', 'arrival_date', 'o2_level_percent', 'co2_level_percent', 'pulp_temp_c', 'atmosphere', 'etd', 'int_pallet_nr', 'pallet_number', 'caliber', 'box_net_weight_g', 'grower', 'grw_boxes_per_pallet', 'total_boxes_per_pallet', 'packing_date', 'peduncular_mold', 'decay', 'soft', 'dehydrated', 'cold_damage', 'bruises', 'open_injury', 'scissor_damage', 'russet_greater_than_4_cm', 'insect_damage', 'sunburn', 'deformed', 'inspected_boxes']

Data types and non-null values:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   idinspection              5000 non-null   int64
 1   inspector_name            5000 non-null   object
 2   fruit                     5000 non-null   object
 3   inspection_date           5000 non-null   object
 4   container                 5000 non-null   object
 5   exporter                  5000 non-null   object
 6   importer                  5000 non-null   object
 7   vessel                    5000 non-null   object
 8   arrival_date              5000 non-null   object
 9   o2_level_percent          5000 non-null   float64
 10  co2_level_percent         4577 non-null   float64
 11  pulp_temp_c               4390 non-null   float64
 12  atmosphere                4493 non-null   object
 13  etd                       5000 non-null   object
 14  int_pallet_nr             5000 non-null   int64
 15  pallet_number             5000 non-null   object
 16  caliber                   5000 non-null   object
 17  box_net_weight_g          5000 non-null   int64
 18  grower                    5000 non-null   object
 19  grw_boxes_per_pallet      5000 non-null   int64
 20  total_boxes_per_pallet    5000 non-null   int64
 21  packing_date              5000 non-null   object
 22  peduncular_mold           493 non-null    float64
 23  decay                     286 non-null    float64
 24  soft                      954 non-null    float64
 25  dehydrated                806 non-null    float64
 26  cold_damage               1195 non-null   float64
 27  bruises                   767 non-null    float64
 28  open_injury               2573 non-null   float64
 29  scissor_damage            465 non-null    float64
 30  russet_greater_than_4_cm  4513 non-null   float64
 31  insect_damage             510 non-null    float64
 32  sunburn                   417 non-null    float64
 33  deformed                  2222 non-null   float64
 34  inspected_boxes           5000 non-null   int64
dtypes: float64(15), int64(6), object(14)
memory usage: 1.3+ MB
None
Column names:

0                 idinspection
1               inspector_name
2                        fruit
3              inspection_date
4                    container
5                     exporter
6                     importer
7                       vessel
8                 arrival_date
9             o2_level_percent
10           co2_level_percent
11                 pulp_temp_c
12                  atmosphere
13                         etd
14               int_pallet_nr
15               pallet_number
16                     caliber
17            box_net_weight_g
18                      grower
19        grw_boxes_per_pallet
20      total_boxes_per_pallet
21                packing_date
22             peduncular_mold
23                       decay
24                        soft
25                  dehydrated
26                 cold_damage
27                     bruises
28                 open_injury
29              scissor_damage
30    russet_greater_than_4_cm
31               insect_damage
32                     sunburn
33                    deformed
34             inspected_boxes
dtype: object

Sample rows:

   idinspection inspector_name      fruit inspection_date     container  \
0             1         Muayad   AVOCADOS      2017-01-02  BMOU963131-2
1             2          Arjun  MANDARINS      2017-01-02  BMOU960422-0
2             3           Jost   AVOCADOS      2017-01-02  BMOU961097-9
3             4          Sarah  MANDARINS      2017-01-02  SUDU962715-3
4             5         Muayad  MANDARINS      2017-01-02  SUDU931477-9

     exporter        importer           vessel arrival_date  o2_level_percent  \
0   SJ EXPORT  FRUITS EXOTICS        MSC CHLOE   2017-01-10               4.0
1   SJ EXPORT          MKVTRB      SANTA CLARA   2018-01-19               3.7
2   SJ EXPORT  FRUITS EXOTICS        MSC CHLOE   2017-01-05               4.4
3  CITRICS CL  FRUITS EXOTICS        MSC CHLOE   2017-01-09               3.9
4   SJ EXPORT  FRUITS EXOTICS  CMA CGM NIAGARA   2017-01-10               4.6

   ...  dehydrated  cold_damage bruises open_injury  scissor_damage  \
0  ...         NaN          NaN     NaN         NaN             NaN
1  ...         NaN          NaN     NaN         NaN             NaN
2  ...         NaN          NaN     NaN         NaN             NaN
3  ...         NaN          NaN     NaN         NaN             NaN
4  ...         NaN          NaN     1.0         NaN             NaN

  russet_greater_than_4_cm insect_damage  sunburn deformed  inspected_boxes
0                      3.0           NaN      NaN      NaN                2
1                      3.0           NaN      NaN      0.0                2
2                      3.0           NaN      NaN      1.0                2
3                      NaN           NaN      NaN      NaN                2
4                      3.0           NaN      NaN      1.0                2

[5 rows x 35 columns]

Statistical summary:

        idinspection inspector_name      fruit inspection_date     container  \
count    5000.000000           5000       5000            5000          5000
unique           NaN              8          3              13            23
top              NaN          Sarah  MANDARINS      2017-01-10  SUDU931036-7
freq             NaN           1443       2486            1997           636
mean     2500.500000            NaN        NaN             NaN           NaN
std      1443.520003            NaN        NaN             NaN           NaN
min         1.000000            NaN        NaN             NaN           NaN
25%      1250.750000            NaN        NaN             NaN           NaN
50%      2500.500000            NaN        NaN             NaN           NaN
75%      3750.250000            NaN        NaN             NaN           NaN
max      5000.000000            NaN        NaN             NaN           NaN

         exporter        importer     vessel arrival_date  o2_level_percent  \
count        5000            5000       5000         5000       5000.000000
unique          5               5         12           12               NaN
top     SJ EXPORT  FRUITS EXOTICS  MSC CHLOE   2017-01-10               NaN
freq         2655            3268       1982         1985               NaN
mean          NaN             NaN        NaN          NaN          4.594780
std           NaN             NaN        NaN          NaN          1.431447
min           NaN             NaN        NaN          NaN          3.700000
25%           NaN             NaN        NaN          NaN          3.900000
50%           NaN             NaN        NaN          NaN          4.000000
75%           NaN             NaN        NaN          NaN          4.400000
max           NaN             NaN        NaN          NaN          8.600000

        ...  dehydrated  cold_damage     bruises  open_injury  scissor_damage  \
count   ...  806.000000  1195.000000  767.000000  2573.000000      465.000000
unique  ...         NaN          NaN         NaN          NaN             NaN
top     ...         NaN          NaN         NaN          NaN             NaN
freq    ...         NaN          NaN         NaN          NaN             NaN
mean    ...    1.225806     1.712134    0.949153     0.963855        2.544086
std     ...    0.848018     1.222683    0.219829     0.286855        0.706110
min     ...    0.000000     0.000000    0.000000     0.000000        1.000000
25%     ...    1.000000     1.000000    1.000000     1.000000        2.000000
50%     ...    1.000000     2.000000    1.000000     1.000000        3.000000
75%     ...    1.000000     2.000000    1.000000     1.000000        3.000000
max     ...    5.000000     5.000000    1.000000     2.000000        6.000000

       russet_greater_than_4_cm insect_damage  sunburn    deformed  \
count               4513.000000    510.000000    417.0  2222.00000
unique                      NaN           NaN      NaN         NaN
top                         NaN           NaN      NaN         NaN
freq                        NaN           NaN      NaN         NaN
mean                   2.836029      1.003922      1.0     1.89604
std                    1.722727      0.062561      0.0     1.26302
min                    1.000000      1.000000      1.0     0.00000
25%                    1.000000      1.000000      1.0     1.00000
50%                    3.000000      1.000000      1.0     2.00000
75%                    3.000000      1.000000      1.0     3.00000
max                    6.000000      2.000000      1.0     7.00000

        inspected_boxes
count       5000.000000
unique              NaN
top                 NaN
freq                NaN
mean           2.014400
std            0.481912
min            1.000000
25%            2.000000
50%            2.000000
75%            2.000000
max            4.000000

[11 rows x 35 columns]

In [184]:
df.shape

(5000, 35)

In [185]:
df.head(5)

,idinspection,inspector_name,fruit,inspection_date,container,exporter,importer,vessel,arrival_date,o2_level_percent,...,dehydrated,cold_damage,bruises,open_injury,scissor_damage,russet_greater_than_4_cm,insect_damage,sunburn,deformed,inspected_boxes
0,1,Muayad,AVOCADOS,2017-01-02,BMOU963131-2,SJ EXPORT,FRUITS EXOTICS,MSC CHLOE,2017-01-10,4.0,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,2
1,2,Arjun,MANDARINS,2017-01-02,BMOU960422-0,SJ EXPORT,MKVTRB,SANTA CLARA,2018-01-19,3.7,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,0.0,2
2,3,Jost,AVOCADOS,2017-01-02,BMOU961097-9,SJ EXPORT,FRUITS EXOTICS,MSC CHLOE,2017-01-05,4.4,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,1.0,2
3,4,Sarah,MANDARINS,2017-01-02,SUDU962715-3,CITRICS CL,FRUITS EXOTICS,MSC CHLOE,2017-01-09,3.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4,5,Muayad,MANDARINS,2017-01-02,SUDU931477-9,SJ EXPORT,FRUITS EXOTICS,CMA CGM NIAGARA,2017-01-10,4.6,...,NaN,NaN,1.0,NaN,NaN,3.0,NaN,NaN,1.0,2

In [186]:
df.describe()

,idinspection,o2_level_percent,co2_level_percent,pulp_temp_c,int_pallet_nr,box_net_weight_g,grw_boxes_per_pallet,total_boxes_per_pallet,peduncular_mold,decay,...,dehydrated,cold_damage,bruises,open_injury,scissor_damage,russet_greater_than_4_cm,insect_damage,sunburn,deformed,inspected_boxes
count,5000.000000,5000.000000,4577.000000,4390.000000,5000.000000,5000.000000,5000.000000,5000.000000,493.000000,286.000000,...,806.000000,1195.000000,767.000000,2573.000000,465.000000,4513.000000,510.000000,417.0,2222.00000,5000.000000
mean,2500.500000,4.594780,7.740966,4.999795,2500.500000,10209.857400,145.092000,145.092000,1.200811,1.055944,...,1.225806,1.712134,0.949153,0.963855,2.544086,2.836029,1.003922,1.0,1.89604,2.014400
std,1443.520003,1.431447,0.790924,0.691874,1443.520003,263.719486,62.351657,62.351657,0.500243,0.230216,...,0.848018,1.222683,0.219829,0.286855,0.706110,1.722727,0.062561,0.0,1.26302,0.481912
min,1.000000,3.700000,6.300000,3.800000,1.000000,9951.000000,120.000000,120.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.0,0.00000,1.000000
25%,1250.750000,3.900000,7.100000,4.600000,1250.750000,9951.000000,120.000000,120.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.0,1.00000,2.000000
50%,2500.500000,4.000000,7.600000,5.000000,2500.500000,10138.500000,120.000000,120.000000,1.000000,1.000000,...,1.000000,2.000000,1.000000,1.000000,3.000000,3.000000,1.000000,1.0,2.00000,2.000000
75%,3750.250000,4.400000,8.600000,5.500000,3750.250000,10451.000000,120.000000,120.000000,1.000000,1.000000,...,1.000000,2.000000,1.000000,1.000000,3.000000,3.000000,1.000000,1.0,3.00000,2.000000
max,5000.000000,8.600000,8.900000,6.200000,5000.000000,10865.000000,300.000000,300.000000,3.000000,2.000000,...,5.000000,5.000000,1.000000,2.000000,6.000000,6.000000,2.000000,1.0,7.00000,4.000000

In [187]:
# STEP 2: Data Cleaning and Preparation
# -------------------------------------
# This step converts date columns to proper datetime format and inspects missing values.

# Convert known date columns to datetime
date_cols = ["inspection_date", "arrival_date", "etd", "packing_date"]

for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors="coerce")

# Check conversion
print("Date columns after conversion:\n")
print(df[date_cols].dtypes)

Date columns after conversion:

inspection_date    datetime64[ns]
arrival_date       datetime64[ns]
etd                datetime64[ns]
packing_date       datetime64[ns]
dtype: object

In [188]:
# Check missing values
print("\nMissing values per column:\n")
print(df.isnull().sum().sort_values(ascending=False))

Missing values per column:

decay                       4714
sunburn                     4583
scissor_damage              4535
peduncular_mold             4507
insect_damage               4490
bruises                     4233
dehydrated                  4194
soft                        4046
cold_damage                 3805
deformed                    2778
open_injury                 2427
pulp_temp_c                  610
atmosphere                   507
russet_greater_than_4_cm     487
co2_level_percent            423
fruit                          0
inspector_name                 0
idinspection                   0
inspection_date                0
grower                         0
box_net_weight_g               0
caliber                        0
pallet_number                  0
int_pallet_nr                  0
etd                            0
arrival_date                   0
o2_level_percent               0
container                      0
exporter                       0
vessel                         0
importer                       0
total_boxes_per_pallet         0
grw_boxes_per_pallet           0
packing_date                   0
inspected_boxes                0
dtype: int64

In [189]:
# Review all data types
print("\nData types of all columns:\n")
print(df.dtypes)

Data types of all columns:

idinspection                         int64
inspector_name                      object
fruit                               object
inspection_date             datetime64[ns]
container                           object
exporter                            object
importer                            object
vessel                              object
arrival_date                datetime64[ns]
o2_level_percent                   float64
co2_level_percent                  float64
pulp_temp_c                        float64
atmosphere                          object
etd                         datetime64[ns]
int_pallet_nr                        int64
pallet_number                       object
caliber                             object
box_net_weight_g                     int64
grower                              object
grw_boxes_per_pallet                 int64
total_boxes_per_pallet               int64
packing_date                datetime64[ns]
peduncular_mold                    float64
decay                              float64
soft                               float64
dehydrated                         float64
cold_damage                        float64
bruises                            float64
open_injury                        float64
scissor_damage                     float64
russet_greater_than_4_cm           float64
insect_damage                      float64
sunburn                            float64
deformed                           float64
inspected_boxes                      int64
dtype: object

### Inspect Key Variables
Objective: Explore key variables individually to better understand their values, data quality, and possible cleaning needs.

We begin by inspecting the atmosphere column, which likely refers to the type or condition of the controlled atmosphere in fruit containers (e.g., regular air, modified atmosphere, etc.).

In [190]:
# STEP 3 - Inspect Key Variables
# First 10 Rows of the atmosphere Column

print(df["atmosphere"].head(10))

0    STARCOOL
1    STARCOOL
2    STARCOOL
3    STARCOOL
4    STARCOOL
5    STARCOOL
6    STARCOOL
7    STARCOOL
8         NaN
9    STARCOOL
Name: atmosphere, dtype: object

In [191]:
# Sample 10 random values

print(df["atmosphere"].sample(10, random_state=1))

2764      STARCOOL
4767      STARCOOL
3814      STARCOOL
3499      STARCOOL
2735      STARCOOL
3922      STARCOOL
2701      STARCOOL
1179      STARCOOL
932       STARCOOL
792     XTENDFRESH
Name: atmosphere, dtype: object

In [192]:
# Inspect the "pulp_temp_c" column: pulp temperature in Â°C

print("\nRandom 10 values from 'pulp_temp_c' column:\n")
print(df["pulp_temp_c"].sample(10, random_state=1))

Random 10 values from 'pulp_temp_c' column:

2764    5.1
4767    5.1
3814    5.1
3499    5.4
2735    5.1
3922    NaN
2701    5.1
1179    4.1
932     5.1
792     4.4
Name: pulp_temp_c, dtype: float64

In [193]:
# Inspect the "co2_level_percent" column: COâ‚‚ concentration percentage

print("\nRandom 10 values from 'co2_level_percent' column:\n")
print(df["co2_level_percent"].sample(10, random_state=1))

Random 10 values from 'co2_level_percent' column:

2764    7.0
4767    6.3
3814    8.1
3499    8.6
2735    8.8
3922    8.8
2701    8.0
1179    7.4
932     NaN
792     8.8
Name: co2_level_percent, dtype: float64

In [194]:
# STEP 4: Missing Values Treatment
# --------------------------------
# Fill NaN values with 0 for defect-related columns, since absence = no damage

# List of defect columns where missing = 0 (no issue reported)
defect_cols = [
    "decay", "sunburn", "scissor_damage", "peduncular_mold", "insect_damage",
    "bruises", "dehydrated", "soft", "cold_damage", "deformed",
    "open_injury", "russet_greater_than_4_cm"
]

# Replace NaN with 0
df[defect_cols] = df[defect_cols].fillna(0)

In [195]:
# Check if any NaNs remain in defect columns
print("\nRemaining NaN values (should be 0) in defect columns:\n")
print(df[defect_cols].isnull().sum())

Remaining NaN values (should be 0) in defect columns:

decay                       0
sunburn                     0
scissor_damage              0
peduncular_mold             0
insect_damage               0
bruises                     0
dehydrated                  0
soft                        0
cold_damage                 0
deformed                    0
open_injury                 0
russet_greater_than_4_cm    0
dtype: int64

The pulp_temp_c, atmosphere and co2_level_percent columns should not be filled with 0, as they simply were not recorded.

What does NaN mean?

pulp_temp_c: Pulp temperature was not measured  
atmosphere: Container atmosphere type was not recorded  
co2_level_percent: Container COâ‚‚ level was not measured

In [196]:
# Check missing values
print("\nMissing values per column:\n")
print(df.isnull().sum().sort_values(ascending=False))

Missing values per column:

pulp_temp_c                 610
atmosphere                  507
co2_level_percent           423
fruit                         0
inspector_name                0
idinspection                  0
inspection_date               0
importer                      0
vessel                        0
exporter                      0
container                     0
o2_level_percent              0
arrival_date                  0
etd                           0
int_pallet_nr                 0
pallet_number                 0
caliber                       0
box_net_weight_g              0
grower                        0
grw_boxes_per_pallet          0
total_boxes_per_pallet        0
packing_date                  0
peduncular_mold               0
decay                         0
soft                          0
dehydrated                    0
cold_damage                   0
bruises                       0
open_injury                   0
scissor_damage                0
russet_greater_than_4_cm      0
insect_damage                 0
sunburn                       0
deformed                      0
inspected_boxes               0
dtype: int64

In [197]:
# Check for Duplicates
# ----------------------------

# Count duplicated rows
num_duplicates = df.duplicated().sum()

print(f"Number of duplicated rows: {num_duplicates}")

Number of duplicated rows: 0

In [198]:
# STEP 5: Convert selected columns to integer type
# List of columns that must be integers
integer_columns = [
    'idinspection', 'int_pallet_nr', 'box_net_weight_g', 'grw_boxes_per_pallet', 
    'total_boxes_per_pallet', 'peduncular_mold', 'decay', 'soft',
    'dehydrated', 'cold_damage', 'bruises', 'open_injury',
    'scissor_damage', 'russet_greater_than_4_cm', 'insect_damage',
    'sunburn', 'deformed', 'inspected_boxes'
]

# Convert to integer (nullable integer to preserve NaNs if any)
df[integer_columns] = df[integer_columns].apply(pd.to_numeric, errors='coerce').astype('Int64')

In [199]:
# STEP 6: Check Data Types and Consistency
# ----------------------------------

# View data types of all columns
print("Column data types:\n")
print(df.dtypes)

Column data types:

idinspection                         Int64
inspector_name                      object
fruit                               object
inspection_date             datetime64[ns]
container                           object
exporter                            object
importer                            object
vessel                              object
arrival_date                datetime64[ns]
o2_level_percent                   float64
co2_level_percent                  float64
pulp_temp_c                        float64
atmosphere                          object
etd                         datetime64[ns]
int_pallet_nr                        Int64
pallet_number                       object
caliber                             object
box_net_weight_g                     Int64
grower                              object
grw_boxes_per_pallet                 Int64
total_boxes_per_pallet               Int64
packing_date                datetime64[ns]
peduncular_mold                      Int64
decay                                Int64
soft                                 Int64
dehydrated                           Int64
cold_damage                          Int64
bruises                              Int64
open_injury                          Int64
scissor_damage                       Int64
russet_greater_than_4_cm             Int64
insect_damage                        Int64
sunburn                              Int64
deformed                             Int64
inspected_boxes                      Int64
dtype: object

In [200]:
# STEP 7: Export cleaned DataFrame to CSV
# Export to CSV with a fixed decimal (e.g. 3.0 instead of 3)

df.to_csv("cleaned_fruit_inspection_data_final.csv", index=False, float_format="%.1f", encoding='utf-8')

In [201]:
# Load the cleaned CSV file
df_check = pd.read_csv("cleaned_fruit_inspection_data_final.csv")

# Detailed info (includes non-null counts)
print("\nDetailed info:")
print(df_check.info())

Detailed info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   idinspection              5000 non-null   int64
 1   inspector_name            5000 non-null   object
 2   fruit                     5000 non-null   object
 3   inspection_date           5000 non-null   object
 4   container                 5000 non-null   object
 5   exporter                  5000 non-null   object
 6   importer                  5000 non-null   object
 7   vessel                    5000 non-null   object
 8   arrival_date              5000 non-null   object
 9   o2_level_percent          5000 non-null   float64
 10  co2_level_percent         4577 non-null   float64
 11  pulp_temp_c               4390 non-null   float64
 12  atmosphere                4493 non-null   object
 13  etd                       5000 non-null   object
 14  int_pallet_nr             5000 non-null   int64
 15  pallet_number             5000 non-null   object
 16  caliber                   5000 non-null   object
 17  box_net_weight_g          5000 non-null   int64
 18  grower                    5000 non-null   object
 19  grw_boxes_per_pallet      5000 non-null   int64
 20  total_boxes_per_pallet    5000 non-null   int64
 21  packing_date              5000 non-null   object
 22  peduncular_mold           5000 non-null   int64
 23  decay                     5000 non-null   int64
 24  soft                      5000 non-null   int64
 25  dehydrated                5000 non-null   int64
 26  cold_damage               5000 non-null   int64
 27  bruises                   5000 non-null   int64
 28  open_injury               5000 non-null   int64
 29  scissor_damage            5000 non-null   int64
 30  russet_greater_than_4_cm  5000 non-null   int64
 31  insect_damage             5000 non-null   int64
 32  sunburn                   5000 non-null   int64
 33  deformed                  5000 non-null   int64
 34  inspected_boxes           5000 non-null   int64
dtypes: float64(3), int64(18), object(14)
memory usage: 1.3+ MB
None

### Step 8 - Export Cleaned Dataset for Visualization

**Objective:**  
Export the cleaned and pre-processed dataset to a CSV file for further analysis and dashboard creation in Tableau.

This file will contain only the cleaned version of the dataset, with consistent data types and missing values properly handled, making it suitable for sharing or visualization purposes.